[theme]

# Primary accent for interactive elements
primaryColor = '#36c2e2'#'#7792E3'

# Background color for the main content area
backgroundColor = '#FFFFFF' #'#270AA0' #'#498069' #'#273346'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#36C3E2' #'#B9F1C0'

# Color used for almost all text
textColor = '#16065B'# '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"